In [60]:
import pandas as pd

df = pd.read_csv("SampleSuperstore.csv")

df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   str
 1   Segment       9994 non-null   str
 2   Country       9994 non-null   str
 3   City          9994 non-null   str
 4   State         9994 non-null   str
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   str
 7   Category      9994 non-null   str
 8   Sub-Category  9994 non-null   str
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 1015.1 KB

In [11]:
#Sales By Region

sales_by_region = df.groupby('Region').Sales.sum()
sales_by_region

Region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

In [38]:
#Find missing values and handle them
df.isnull().sum()

#Drop rows with missing values
#df_cleaned = df.dropna()

#Fill missing values
#df['Quantity'] = df['Quantity'].fillna(0)

#df

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [71]:
#Create a new column Profit Margin (%) and find top 10 profitable transactions.

df['Profit_Margin'] = (df['Profit']/df['Sales'])*100

top_profit_margin = df.sort_values(by='Profit_Margin', ascending=False).head(10)
top_profit_margin

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit_Margin
9228,Same Day,Home Office,United States,Los Angeles,California,90049,West,Office Supplies,Art,6.72,4,0.0,3.36,50.0
3934,Standard Class,Consumer,United States,Bakersfield,California,93309,West,Office Supplies,Labels,74.00,5,0.0,37.00,50.0
9951,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Office Supplies,Binders,17.38,2,0.0,8.69,50.0
3747,Second Class,Corporate,United States,Inglewood,California,90301,West,Furniture,Furnishings,198.46,2,0.0,99.23,50.0
8947,Standard Class,Corporate,United States,New Bedford,Massachusetts,2740,East,Office Supplies,Binders,12.30,5,0.0,6.15,50.0
770,Standard Class,Corporate,United States,Des Moines,Iowa,50315,Central,Office Supplies,Binders,18.28,2,0.0,9.14,50.0
764,Second Class,Corporate,United States,Bossier City,Louisiana,71111,South,Office Supplies,Envelopes,50.94,3,0.0,25.47,50.0
8656,Same Day,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Paper,48.94,1,0.0,24.47,50.0
8687,Same Day,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Fasteners,17.90,5,0.0,8.95,50.0
720,Standard Class,Home Office,United States,Los Angeles,California,90045,West,Office Supplies,Paper,146.82,3,0.0,73.41,50.0

In [72]:
#

avg_profit = df.groupby('Region')['Profit'].mean().sort_values(ascending=False)
avg_profit

hg_avg_profit = avg_profit.max()
top_region = avg_profit.idxmax()
print(top_region, hg_avg_profit)

West 33.84903181392445

In [ ]:
#Products with highest sales but below-average profit.

product_analysis = df.groupby('Sub-Category')[['Sales', 'Profit']].sum()

low_profit_products = product_analysis[
    product_analysis['Profit'] < product_analysis['Profit'].mean()
].sort_values(by='Sales', ascending=False)

low_profit_products.head(10)

                    Sales      Profit
Sub-Category
Tables        206965.5320 -17725.4811
Machines      189238.6310   3384.7569
Bookcases     114879.9963  -3472.5560
Furnishings    91705.1640  13059.1436
Supplies       46673.5380  -1189.0995
Art            27118.7920   6527.7870
Envelopes      16476.4020   6964.1767
Labels         12486.3120   5546.2540
Fasteners       3024.2800    949.5182

In [74]:
#High sales but loss-making transactions

loss_making_trans = df [
    (df['Sales'] > df['Sales'].mean()) & (df['Profit'] > 0)
]
loss_making_trans

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit_Margin
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.960,2,0.0,41.9136,16.0
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.940,3,0.0,219.5820,30.0
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.152,6,0.2,90.7152,10.0
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.184,9,0.2,85.3092,5.0
11,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,911.424,4,0.2,68.3568,7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9973,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,271.960,5,0.2,27.1960,10.0
9976,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,249.584,2,0.2,31.1980,12.5
9979,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Office Supplies,Binders,437.472,14,0.2,153.1152,35.0
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.576,2,0.2,19.3932,7.5
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.160,2,0.0,72.9480,30.0

In [ ]:
#Most profitable Category + Segment combination

cat_seg_profit = df.groupby(['Category', 'Segment'])['Profit'].sum().sort_values(ascending=False)
cat_seg_profit

Category         Segment
Technology       Consumer       70797.8096
Office Supplies  Consumer       56330.3210
Technology       Corporate      44166.9980
Office Supplies  Corporate      40227.3202
Technology       Home Office    30490.1405
Office Supplies  Home Office    25933.1596
Furniture        Corporate       7584.8158
                 Consumer        6991.0786
                 Home Office     3875.3784
Name: Profit, dtype: float64

In [ ]:
#3 regions that the company improve

region_rec = df.groupby('Region')[['Sales', 'Profit']].sum()
region_rec['profit_margin'] = (region_rec['Profit']/ region_rec['Sales'])*100
region_rec.sort_values(by='profit_margin', ascending=False).head(3)

              Sales       Profit  profit_margin
Region
West    725457.8245  108418.4489      14.944831
East    678781.2400   91522.7800      13.483399
South   391721.9050   46749.4303      11.934342